---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: aurora-ipu6
description: Aurora with IPU6 camera packages

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  - type: dnf
    repos:
      nonfree: rpmfusion
    install:
      packages:
        - akmod-intel-ipu6
        - ipu6-camera-hal
        - mokutil
        - openssl
        - kmodtool

  - type: signing
