---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: aurora-stable-ipu6
description: Aurora with IPU6 camera packages

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  - type: dnf
    repos:
      nonfree: rpmfusion
    install:
      packages:
        - ipu6-camera-hal
        - akmods
        - kmodtool

  - type: script
    snippets:
      - mkdir -p /tmp/ipu6-akmod && cd /tmp/ipu6-akmod
      - dnf5 -y --refresh download akmod-intel-ipu6
      - rpm -Uvh --noscripts --notriggers ./*.rpm
      - rm -rf /tmp/ipu6-akmod

  - type: signing
