---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: aurora-stable-ipu6
description: Aurora with IPU6 camera packages

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  - type: dnf
    repos:
      nonfree: rpmfusion
    install:
      packages:
        - ipu6-camera-hal

  - type: script
    snippets:
      - dnf5 -y --refresh --setopt=tsflags=noscripts install akmod-intel-ipu6

  - type: signing
