name: aurora-stable-ipu6
description: Aurora with Intel IPU6 camera drivers

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  - type: dnf
    repos:
      nonfree: rpmfusion
    install:
      packages:
        - ipu6-camera-hal

  - type: script
    scripts:
      - build-ipu6.sh

  - type: signing
